DROP TABLE IF EXISTS users;
CREATE TABLE users (id serial PRIMARY_KEY, username VARCHAR(255), password VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS weiland;
CREATE TABLE weilands (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL);
